#!/bin/bash

. /root/.bash_profile

#rootのcrontabに起動設定を書くなどして、rootで動くようにしないとログが残らない。


usage_exit() {
        echo "Usage: $0 [-f]" 1>&2
        echo 'fleshclamとclamscanを実行する。-f 設定(実行時間の制限を無視する。)' 1>&2
        exit 1
}

ENABLE_f="f"


while getopts "f" OPT
do
    case $OPT in
        f)  ENABLE_f="t"
            ;;
        :|\?) usage_exit
            ;;
    esac
done

shift $((OPTIND - 1))

LOGDIR=/var/log/clamav-scan-log/

LOGFILE=${LOGDIR}`date +%Y%m%d%H%M%S`.log

if [ ! -e ${LOGDIR} ]; then
`mkdir ${LOGDIR}`
fi

touch ${LOGFILE}

if [ "${ENABLE_f}" != "t" ]; then  
 #今の時間(何時?)
 NowHour=`date +%k`
 #割る数
 Dev=4
 mod=$(( ${NowHour} % ${Dev} ))
 #割る数で割り切れない時間なら起動しない。
 if [ ! "0" -eq ${mod} ]; then  
   echo ${NowHour} " は、" ${Dev}"で割り切れる時間ではありません。">> ${LogFile}
   exit 1
fi
fi

#多重起動防止機講
# 同じ名前のプロセスが起動していたら起動しない。
_lockfile="/tmp/`basename $0`.lock"
ln -s /dummy $_lockfile 2> /dev/null || { echo 'Cannot run multiple instance.'  >>${LOGFILE}; exit 9; }
trap "rm $_lockfile; exit" 1 2 3 15


# ファイル更新日時が5000日を越えたログファイルを削除
PARAM_DATE_NUM=5000
find ${LOGDIR} -name "*.log" -type f -mtime +${PARAM_DATE_NUM} -exec rm -f {} \;

# DB update
# CentOS(epelからインストール)の場合、freshclamのインストール時に、3時間ごとの自動更新が登録されるのであまり意味が無いが、念のため。
# debian系でfreshclam実行時に下記のようなエラーが出るようならRETRY_FRESHCLAMを0以外に設定する。
# ERROR: /var/log/clamav/freshclam.log is locked by another process
# ERROR: Problem with internal logger (UpdateLogFile = /var/log/clamav/freshclam.log).
RETRY_FRESHCLAM=0
if [ ! "0" -eq ${RETRY_FRESHCLAM} ]; then  
	echo "freshclam失敗時は、freshclamログ再作成後リトライ。" >> ${LOGFILE} 2>&1
	FRESHCLAM_LOGFILE="/var/log/clamav/freshclam.log"
	freshclam >> ${LOGFILE} 2>&1 || rm -f ${FRESHCLAM_LOGFILE} && touch ${FRESHCLAM_LOGFILE} && chown clamav:clamav ${FRESHCLAM_LOGFILE} && freshclam >> ${LOGFILE} 2>&1
else
	echo "freshclam失敗時は、リトライしない。" >> ${LOGFILE} 2>&1
	freshclam >> ${LOGFILE} 2>&1
fi

# virus scan
#感染したファイルのみログに記載する。
clamscan / -r --infected --remove --exclude-dir='/sys|/proc|/dev' >> ${LOGFILE} 2>&1

#ログファイルの内容を表示
cat ${LOGFILE}

#ログファイルの読み込みは全員可能にする。
chmod o+r ${LOGFILE}

rm $_lockfile
