#!/bin/bash

readonly ROOT_HOME='/root'
readonly ROOT_BASH_PROFILE_PATH="${ROOT_HOME}/.bash_profile"
readonly ROOT_PROFILE_PATH="${ROOT_HOME}/.profile"

if [ -f "${ROOT_BASH_PROFILE_PATH}" ]; then
	source "${ROOT_BASH_PROFILE_PATH}" >/dev/null 2>&1 || exit 200
elif [ -f "${ROOT_PROFILE_PATH}" ]; then
	source "${ROOT_PROFILE_PATH}" >/dev/null 2>&1 || exit 210
else
	exit 220
fi

PROCNAME="${1}"

if [ -z "${PROCNAME}" ]; then
	echo "String Error."
	exit 1
fi

LOCKFILE="/tmp/${PROCNAME}.lock"
ps_list=$(ps aux | grep ${PROCNAME} | grep -v grep | grep -v "${BASH_SOURCE[0]##*/}")
ps_count=$(echo "${ps_llist}" | wc -l)
if [ $ps_count -eq 0 ]; then # 対象プロセスが存在しない場合
	rm -f "${LOCKFILE}"
	exit 0
fi
